import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const fixture = JSON.parse(fs.readFileSync(process.env.SRD_BROWSER_FIXTURE || new URL('../../.local/e2e-fixture.json', import.meta.url)));
const mailUrl = process.env.SRD_MAILPIT_URL || 'http://127.0.0.1:8125';

async function login(page, role) {
  await page.goto(`/j/${fixture.codeA || 'srd-e2e-a'}/login`);
  await page.getByLabel('Correo electrónico', { exact: true }).fill(fixture.users[role].email);
  await page.getByLabel('Contraseña', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'términos y condiciones', exact: true }).click();
  await page.getByRole('button', { name: 'Aceptar términos', exact: true }).click();
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Ingresa tu código' })).toBeVisible();
  let message;
  await expect.poll(async () => {
    const list = await (await page.request.get(`${mailUrl}/api/v1/messages`)).json();
    message = list.messages?.find(item => item.Subject === 'Tu código de seguridad de SRD' && item.To.some(to => to.Address === fixture.users[role].email));
    return !!message;
  }, { timeout: 85000 }).toBe(true);
  const content = await (await page.request.get(`${mailUrl}/api/v1/message/${message.ID}`)).json();
  await page.getByLabel('Código de verificación').fill(content.Text.match(/\b\d{6}\b/)[0]);
  await page.getByRole('button', { name: 'Confirmar código' }).click();
  await expect(page.locator('.sidebar').getByRole('button', { name: 'Home', exact: true })).toBeVisible();
}

test('calendar month, week and agenda with editable events and revocable delegation', async ({ page, browser }) => {
  test.setTimeout(240000);
  const title = `Reunión de prueba ${Date.now()}`;
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page, 'admin');
  await page.locator('.sidebar').getByRole('button', { name: 'Calendario' }).click();
  await expect(page.getByRole('heading', { name: 'Calendario', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Quién puede editar el calendario' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear evento' }).click();
  await page.getByRole('dialog').getByLabel('Título', { exact: true }).fill(title);
  await page.getByRole('dialog').getByLabel('Título (EN)').fill(`Test meeting ${Date.now()}`);
  const start = await page.getByRole('dialog').getByLabel('Inicio').inputValue();
  const tomorrow = new Date(start.slice(0, 10) + 'T12:00:00Z');
  tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
  const eventDay = tomorrow.toISOString().slice(0, 10);
  await page.getByRole('dialog').getByLabel('Inicio').fill(`${eventDay}T09:00`);
  await page.getByRole('dialog').getByLabel('Final').fill(`${eventDay}T10:00`);
  await page.getByRole('dialog').getByLabel('Buscar integrante').fill('Prueba Viewer');
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Añadir a Prueba Viewer' })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Añadir a Prueba Viewer' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar evento' }).click();
  await expect(page.getByRole('dialog', { name: 'Detalle del evento' }).getByText(title)).toBeVisible();
  await expect(page.getByRole('dialog', { name: 'Detalle del evento' }).getByText('Participantes: Prueba Viewer (Pendiente)')).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar' }).click();
  const inviteContext = await browser.newContext({ baseURL: process.env.SRD_TEST_URL || 'http://127.0.0.1:5173' });
  const invitee = await inviteContext.newPage();
  invitee.on('pageerror', error => errors.push(error.message));
  await login(invitee, 'viewer');
  await expect.poll(async () => {
    const response = await invitee.request.get('/api/v1/notifications');
    const json = await response.json();
    return json.data?.items?.some(item => item.kind === 'invitation' && item.title === title) ?? false;
  }, { timeout: 90000, intervals: [1000, 2000, 5000] }).toBe(true);
  await invitee.getByRole('button', { name: /^Notificaciones/ }).click();
  const inbox = invitee.getByRole('region', { name: 'Bandeja de notificaciones' });
  await expect(inbox.getByText(`Te invitaron al evento: ${title}`)).toBeVisible();
  const invitationNotice = inbox.locator('li').filter({ hasText: `Te invitaron al evento: ${title}` });
  await invitationNotice.getByRole('button', { name: 'Marcar leído' }).click();
  await expect(invitationNotice.getByRole('button', { name: 'Marcar leído' })).toHaveCount(0);
  await inbox.getByRole('checkbox', { name: 'Recordatorios de 24 horas y 1 hora' }).uncheck();
  await inbox.getByRole('button', { name: 'Guardar preferencias' }).click();
  await expect(inbox.getByRole('button', { name: 'Guardar preferencias' })).toBeDisabled();
  await invitee.getByRole('button', { name: /^Notificaciones/ }).click();
  await invitee.getByRole('button', { name: /^Notificaciones/ }).click();
  await expect(invitee.getByRole('region', { name: 'Bandeja de notificaciones' }).getByRole('checkbox', { name: 'Recordatorios de 24 horas y 1 hora' })).not.toBeChecked();
  await invitee.getByRole('button', { name: /^Notificaciones/ }).click();
  await invitee.locator('.sidebar').getByRole('button', { name: 'Configuración' }).click();
  await invitee.getByLabel('Preferencia de presencia').selectOption('dnd');
  await invitee.getByRole('button', { name: 'Guardar perfil' }).click();
  await expect(invitee.getByRole('button', { name: 'Notificaciones, No molestar' })).toBeVisible();
  await expect(invitee.locator('.notification-count')).toHaveCount(0);
  await invitee.getByRole('button', { name: 'Notificaciones, No molestar' }).click();
  await expect(invitee.getByRole('region', { name: 'Bandeja de notificaciones' }).getByText('1 sin leer')).toBeVisible();
  await invitee.getByRole('button', { name: 'Notificaciones, No molestar' }).click();
  await invitee.locator('.sidebar').getByRole('button', { name: 'Calendario' }).click();
  const invitation = invitee.getByRole('region', { name: 'Mis invitaciones' }).filter({ hasText: title });
  await expect(invitation.getByText('Pendiente')).toBeVisible();
  await invitation.getByRole('button', { name: 'Aceptar' }).click();
  await expect(invitation.getByText('Aceptada')).toBeVisible();
  await page.reload();
  await page.locator('.sidebar').getByRole('button', { name: 'Calendario' }).click();
  await page.getByRole('button', { name: 'Semana', exact: true }).click();
  await expect(page.locator('.calendar-week').getByRole('button', { name: new RegExp(title) })).toBeVisible();
  await page.getByRole('button', { name: 'Agenda', exact: true }).click();
  await expect(page.locator('.calendar-agenda').getByRole('button', { name: new RegExp(title) })).toBeVisible();
  await page.locator('.calendar-agenda').getByRole('button', { name: new RegExp(title) }).click();
  await expect(page.getByRole('dialog', { name: 'Detalle del evento' }).getByText('Participantes: Prueba Viewer (Aceptada)')).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Editar' }).click();
  await page.getByRole('dialog').getByLabel('Título', { exact: true }).fill(title + ' editada');
  await page.getByRole('dialog').getByRole('button', { name: 'Quitar a Prueba Viewer' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar evento' }).click();
  await expect(page.getByRole('dialog', { name: 'Detalle del evento' }).getByText(title + ' editada')).toBeVisible();
  await expect(page.getByRole('dialog', { name: 'Detalle del evento' }).getByText('Participantes: Sin participantes asignados')).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar evento' }).click();
  await expect(page.getByRole('dialog').getByText('Estado: Cancelado')).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar' }).click();
  await page.getByLabel('Consultor').check();
  await page.getByRole('button', { name: 'Guardar permisos' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Permisos del calendario guardados' })).toBeVisible();
  const viewer = invitee;
  try {
    await viewer.reload();
    await viewer.locator('.sidebar').getByRole('button', { name: 'Calendario' }).click();
    await expect(viewer.getByRole('button', { name: 'Crear evento' })).toBeVisible();
    await page.getByLabel('Consultor').uncheck();
    await page.getByRole('button', { name: 'Guardar permisos' }).click();
    await viewer.reload();
    await viewer.locator('.sidebar').getByRole('button', { name: 'Calendario' }).click();
    await expect(viewer.getByRole('button', { name: 'Crear evento' })).toHaveCount(0);
  } finally { await inviteContext.close(); }
  await page.setViewportSize({ width: 360, height: 800 });
  await expect(page.getByRole('heading', { name: 'Calendario', exact: true })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(2);
  expect(errors).toEqual([]);
});
