import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
const fixture=JSON.parse(fs.readFileSync(process.env.SRD_BROWSER_FIXTURE));
const mailUrl=process.env.SRD_MAILPIT_URL||'http://localhost:8025';
async function login(page){
 await page.goto(`/j/${fixture.codeA}/login`);
 await page.getByLabel('Correo electrónico',{exact:true}).fill(fixture.users.admin.email);
 await page.getByLabel('Contraseña',{exact:true}).fill(fixture.password);
 await page.getByRole('button',{name:'términos y condiciones',exact:true}).click();
 await page.getByRole('button',{name:'Aceptar términos',exact:true}).click();
 await page.getByRole('button',{name:'Ingresar',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Ingresa tu código'})).toBeVisible();
 let message;
 await expect.poll(async()=>{const list=await(await page.request.get(`${mailUrl}/api/v1/messages`)).json();message=list.messages?.find(item=>item.Subject==='Tu código de seguridad de SRD'&&item.To.some(to=>to.Address===fixture.users.admin.email));return !!message;},{timeout:85000}).toBe(true);
 const content=await(await page.request.get(`${mailUrl}/api/v1/message/${message.ID}`)).json();
 await page.getByLabel('Código de verificación').fill(content.Text.match(/\b\d{6}\b/)[0]);
 await page.getByRole('button',{name:'Confirmar código'}).click();
 await expect(page.locator('.sidebar').getByRole('button',{name:'Home',exact:true})).toBeVisible();
}
test('exact 20 MiB Office upload and download preserves bytes and rejects one extra byte',async({page})=>{
 test.setTimeout(300000);await login(page);
 const max=20*1024*1024,path='.local/office-boundary.docx',overPath='.local/office-over-limit.docx';
 expect(fs.statSync(path).size).toBe(max);expect(fs.statSync(overPath).size).toBe(max+1);
 const hash=createHash('sha256').update(fs.readFileSync(path)).digest('hex');
 await page.getByRole('button',{name:'Carpeta',exact:true}).click();
 const panel=page.getByRole('region',{name:'Archivos privados'});
 await expect(panel.getByText('0 archivos en esta ubicación.')).toBeVisible();
 let posts=0;const count=request=>{if(new URL(request.url()).pathname==='/api/v1/folder-documents'&&request.method()==='POST')posts++;};
 page.on('request',count);
 await panel.getByLabel('Documento, imagen o audio',{exact:true}).setInputFiles(overPath);
 await panel.getByRole('button',{name:'Guardar archivo',exact:true}).click();
 await expect(panel.getByRole('alert')).toContainText('hasta 20 MB');expect(posts).toBe(0);
 await panel.getByLabel('Documento, imagen o audio',{exact:true}).setInputFiles(path);
 const uploadStarted=Date.now();
 const uploaded=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/v1/folder-documents'&&response.request().method()==='POST',{timeout:90000});
 await panel.getByRole('button',{name:'Guardar archivo',exact:true}).click();
 expect((await uploaded).status()).toBe(200);const uploadSeconds=(Date.now()-uploadStarted)/1000;
 await expect(panel.getByText('Documento guardado y analizado.')).toBeVisible();expect(posts).toBe(1);page.off('request',count);
 const listing=await(await page.request.get('/api/v1/folder-documents')).json();
 expect(listing.data.total).toBe(1);const document=listing.data.items[0];
 expect(document.bytes).toBe(max);expect(document.sha256).toBe(hash);expect(document.version).toBe(1);
 const [download]=await Promise.all([page.waitForEvent('download'),panel.getByRole('button',{name:'Descargar office-boundary.docx',exact:true}).click()]);
 expect(download.suggestedFilename()).toBe('office-boundary.docx');
 const stream=await download.createReadStream(),downloadHash=createHash('sha256');let downloaded=0;
 for await(const chunk of stream){downloaded+=chunk.length;downloadHash.update(chunk);}expect(downloaded).toBe(max);expect(downloadHash.digest('hex')).toBe(hash);
 const token=(await(await page.request.get('/api/v1/csrf')).json()).data.token;
 const rejected=await page.request.post('/api/v1/folder-documents',{headers:{'X-CSRF-TOKEN':token},data:{id:crypto.randomUUID(),folder_id:null,name:'Over.docx',content:fs.readFileSync(overPath).toString('base64')},timeout:90000});
 expect(rejected.status()).toBe(422);
 const final=await(await page.request.get('/api/v1/folder-documents')).json();expect(final.data.total).toBe(1);expect(final.data.items[0].sha256).toBe(hash);
 await page.reload();await page.getByRole('button',{name:'Carpeta',exact:true}).click();
 await expect(panel.getByRole('button',{name:'Descargar office-boundary.docx',exact:true})).toBeVisible();
 await page.setViewportSize({width:360,height:800});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'.local/document-boundary-mobile.png'});
 await expect.poll(async()=>{const events=await(await page.request.get(`/api/v1/audit-events?service=files&action=document.created`)).json();return events.data.items.filter(item=>item.resource_id===document.id).length;},{timeout:85000,intervals:[2000,5000]}).toBe(1);
 await test.info().attach('boundary-verification',{body:JSON.stringify({bytes:max,sha256:hash,uploadSeconds,downloaded,overLimitBytes:max+1,overLimitStatus:rejected.status()}),contentType:'application/json'});
});
