import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
const fixture=JSON.parse(fs.readFileSync(process.env.SRD_BROWSER_FIXTURE));
const mailUrl=process.env.SRD_MAILPIT_URL||'http://localhost:8025';
async function login(page){
 await page.goto(`/j/${fixture.codeA}/login`);
 await page.getByLabel('Correo electrónico',{exact:true}).fill(fixture.users.admin.email);
 await page.getByLabel('Contraseña',{exact:true}).fill(fixture.password);
 await page.getByRole('button',{name:'términos y condiciones',exact:true}).click();
 await page.getByRole('button',{name:'Aceptar términos',exact:true}).click();
 await page.getByRole('button',{name:'Ingresar',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Ingresa tu código'})).toBeVisible();
 let message;
 await expect.poll(async()=>{const list=await(await page.request.get(`${mailUrl}/api/v1/messages`)).json();message=list.messages?.find(item=>item.Subject==='Tu código de seguridad de SRD'&&item.To.some(to=>to.Address===fixture.users.admin.email));return !!message;},{timeout:85000}).toBe(true);
 const content=await(await page.request.get(`${mailUrl}/api/v1/message/${message.ID}`)).json();
 await page.getByLabel('Código de verificación').fill(content.Text.match(/\b\d{6}\b/)[0]);
 await page.getByRole('button',{name:'Confirmar código'}).click();
 await expect(page.locator('.sidebar').getByRole('button',{name:'Home',exact:true})).toBeVisible();
}
test('private folder image strips original bytes and can be renamed moved downloaded and deleted',async({page})=>{
 test.setTimeout(240000);await login(page);
 const headers={'X-CSRF-TOKEN':(await(await page.request.get('/api/v1/csrf')).json()).data.token};
 const folderId=crypto.randomUUID();
 expect((await page.request.post('/api/v1/folders',{headers,data:{id:folderId,name:'Fotos',parent_id:null}})).status()).toBe(200);
 const original=fs.readFileSync('.local/folder-image.jpg');
 const invalid=await page.request.post('/api/v1/folder-documents',{headers,data:{id:crypto.randomUUID(),folder_id:null,name:'Disfraz.png',content:original.toString('base64')}});
 expect(invalid.status()).toBe(422);
 await page.getByRole('button',{name:'Carpeta',exact:true}).click();
 const panel=page.getByRole('region',{name:'Archivos privados'});
  await panel.getByLabel('Documento, imagen o audio',{exact:true}).setInputFiles('.local/folder-image.jpg');
 await panel.getByRole('button',{name:'Guardar archivo',exact:true}).click();
 await expect(panel.getByText('Imagen guardada y analizada como PNG.')).toBeVisible();
 await expect(panel.getByText('1 archivo en esta ubicación.')).toBeVisible();
 const listing=await(await page.request.get('/api/v1/folder-documents')).json();
 expect(listing.data.total).toBe(1);const item=listing.data.items[0];
 expect(item.name).toBe('folder-image.png');expect(item.mime).toBe('image/png');expect(item.version).toBe(1);
 const result=await(await page.request.get(`/api/v1/folder-documents/${item.id}/download`)).json();
 const normalized=Buffer.from(result.data.content,'base64');
 expect(normalized.subarray(0,8)).toEqual(Buffer.from('89504e470d0a1a0a','hex'));
 expect(normalized.equals(original)).toBe(false);
 expect(result.data.bytes).toBe(normalized.length);
 expect(result.data.sha256).toBe(createHash('sha256').update(normalized).digest('hex'));
 await panel.getByRole('button',{name:'Renombrar imagen folder-image.png',exact:true}).click();
 const rename=page.getByRole('dialog',{name:'Renombrar imagen: folder-image.png'});
 await rename.getByLabel('Nuevo nombre del archivo').fill('Asamblea.png');
 await rename.getByRole('button',{name:'Guardar nuevo nombre'}).click();
 await expect(panel.getByRole('button',{name:'Mover imagen Asamblea.png',exact:true})).toBeVisible();
 await panel.getByRole('button',{name:'Mover imagen Asamblea.png',exact:true}).click();
 const move=page.getByRole('dialog',{name:'Mover imagen: Asamblea.png'});
 await move.getByRole('button',{name:'Abrir destino Fotos',exact:true}).click();
 await move.getByRole('button',{name:'Mover a esta ubicación',exact:true}).click();
 await expect(panel.getByText('0 archivos en esta ubicación.')).toBeVisible();
 await page.getByRole('button',{name:'Fotos',exact:true}).click();
 await expect(panel.getByText('1 archivo en esta ubicación.')).toBeVisible();
 await page.setViewportSize({width:360,height:800});
 await panel.getByRole('button',{name:'Ver imagen Asamblea.png',exact:true}).click();
 const preview=page.getByRole('dialog',{name:'Vista previa: Asamblea.png'});
 const picture=preview.getByRole('img',{name:'Asamblea.png'});
 await expect(picture).toBeVisible();
 await expect.poll(()=>picture.evaluate(image=>[image.naturalWidth,image.naturalHeight])).toEqual([4,3]);
 expect(await picture.getAttribute('src')).toMatch(/^data:image\/png;base64,/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'.local/folder-image-preview-mobile.png'});
 await page.keyboard.press('Escape');await expect(preview).not.toBeVisible();
 const [download]=await Promise.all([page.waitForEvent('download'),panel.getByRole('button',{name:'Descargar Asamblea.png',exact:true}).click()]);
 expect(download.suggestedFilename()).toBe('Asamblea.png');
 const stream=await download.createReadStream(),hash=createHash('sha256');let count=0;
 for await(const chunk of stream){count+=chunk.length;hash.update(chunk);}
 expect(count).toBe(normalized.length);expect(hash.digest('hex')).toBe(result.data.sha256);
 await panel.getByRole('button',{name:'Eliminar imagen Asamblea.png',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Eliminar imagen: Asamblea.png'});
 await expect(dialog.getByRole('button',{name:'Sí, eliminar archivo'})).toBeDisabled();
 await dialog.getByLabel('Confirmo que quiero eliminar este archivo.').check();
 await page.setViewportSize({width:360,height:800});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'.local/folder-image-mobile.png'});
 await dialog.getByRole('button',{name:'Sí, eliminar archivo'}).click();
 await expect(panel.getByText('0 archivos en esta ubicación.')).toBeVisible();
 expect((await page.request.get(`/api/v1/folder-documents/${item.id}/download`)).status()).toBe(404);
 expect((await page.request.delete(`/api/v1/folder-documents/${item.id}`,{headers,data:{version:3,confirm:true}})).status()).toBe(404);
 await expect.poll(async()=>{const events=await(await page.request.get('/api/v1/audit-events?service=files&action=document.deleted')).json();return events.data.items.filter(event=>event.resource_id===item.id).length;},{timeout:85000,intervals:[2000,5000]}).toBe(1);
 const retained=await page.request.post('/api/v1/folder-documents',{headers,data:{id:crypto.randomUUID(),folder_id:folderId,name:'Conservada.jpg',content:original.toString('base64')}});
 expect(retained.status()).toBe(200);
 expect((await retained.json()).data.mime).toBe('image/png');
 const saved=await(await page.request.get('/api/v1/folder-documents',{params:{folder_id:folderId}})).json();
 expect(saved.data.items.some(file=>file.name==='Conservada.png'&&file.mime==='image/png')).toBe(true);
});
