import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const fixture = JSON.parse(fs.readFileSync(process.env.SRD_BROWSER_FIXTURE || new URL('../../.local/e2e-fixture.json', import.meta.url)));
test('superadmin creates a junta, invites its administrator, suspends and reactivates it', async ({ page, request, browser }) => {
  test.skip(!process.env.SRD_TEST_URL?.includes(':8080'), 'Requiere Compose y correo local.');
  test.setTimeout(240000);
  const code = `junta-${Date.now()}`;
  const email = `${code}@srd-e2e.test`;
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`/j/${fixture.codeA || 'srd-e2e-a'}/login`);
  await page.getByLabel('Correo electrónico', { exact: true }).fill(fixture.users.superadmin.email);
  await page.getByLabel('Contraseña', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'términos y condiciones', exact: true }).click();
  await page.getByRole('button', { name: 'Aceptar términos', exact: true }).click();
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Ingresa tu código' })).toBeVisible();
  let mail;
  const mailbox = process.env.SRD_MAILPIT_URL;
  await expect.poll(async () => {
    const list = await (await request.get(`${mailbox}/api/v1/messages`)).json();
    mail = list.messages?.find(m => m.Subject === 'Tu código de seguridad de SRD' && m.To.some(t => t.Address === fixture.users.superadmin.email));
    return !!mail;
  }).toBe(true);
  const content = await (await request.get(`${mailbox}/api/v1/message/${mail.ID}`)).json();
  await page.getByLabel('Código de verificación').fill(content.Text.match(/\b\d{6}\b/)[0]);
  await page.getByRole('button', { name: 'Confirmar código' }).click();
  await page.getByRole('button', { name: 'Configuración', exact: true }).click();
  const panel = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Administración de juntas', exact: true }) });
  await panel.getByLabel('Nombre de la junta', { exact: true }).fill(code);
  await panel.getByLabel('Código de junta', { exact: true }).fill(code);
  await panel.getByLabel('Términos de uso iniciales').fill('Términos sintéticos para probar la administración de juntas.');
  await panel.getByRole('button', { name: 'Crear junta', exact: true }).click();
  await expect(panel.getByRole('status')).toContainText('creada');
  await expect(panel.getByRole('button', { name: 'Crear junta', exact: true })).toBeEnabled();
  const row = panel.getByRole('row').filter({ has: page.getByRole('link', { name: code, exact: true }) });
  // The platform list is alphabetical and can contain multiple pages of preserved fixtures.
  while (await row.count() === 0) {
    const next = panel.getByRole('button', { name: 'Siguiente', exact: true });
    await expect(next).toBeEnabled();
    const changed = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v1/platform/organizations' && response.request().method() === 'GET');
    await next.click();
    const result = (await (await changed).json()).data;
    await expect(panel.getByText(`Página ${result.current_page} de ${result.last_page}`, { exact: true })).toBeVisible();
  }
  await row.getByRole('button', { name: 'Invitar administrador', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Correo del administrador').fill(email);
  await page.getByRole('button', { name: 'Enviar invitación de administrador' }).click();
  await expect(panel.getByRole('status')).toContainText('cola de envío');
  let invitation;
  await expect.poll(async () => {
    const list = await (await request.get(`${mailbox}/api/v1/messages`)).json();
    invitation = list.messages?.find(m => m.Subject === 'Invitación privada a SRD' && m.To.some(t => t.Address === email));
    return !!invitation;
  }, { timeout: 85000, intervals: [1000, 2000] }).toBe(true);
  const invitationContent = await (await request.get(`${mailbox}/api/v1/message/${invitation.ID}`)).json();
  const link = invitationContent.HTML.match(/href="([^"]+\/invite#[^"]+)"/)[1].replaceAll('&amp;', '&');
  const guestContext = await browser.newContext({ baseURL: process.env.SRD_TEST_URL });
  try {
  const guest = await guestContext.newPage();
  guest.on('pageerror', e => errors.push(e.message));
  await guest.goto(link);
  await guest.getByLabel('Nombre de la cuenta').fill('Administrador sintético de nueva junta');
  await guest.getByLabel('Crea tu contraseña', { exact: true }).fill(fixture.password);
  await guest.getByLabel('Repite la contraseña', { exact: true }).fill(fixture.password);
  await guest.getByRole('button', { name: 'Leer términos de la invitación' }).click();
  await guest.getByRole('button', { name: 'Aceptar estos términos' }).click();
  await guest.getByRole('button', { name: 'Aceptar invitación privada' }).click();
  await expect(guest.getByRole('status').filter({ hasText: 'Invitación aceptada' })).toBeVisible();
  await guest.getByRole('button', { name: 'Continuar al inicio de sesión' }).click();
  await guest.getByLabel('Correo electrónico', { exact: true }).fill(email);
  await guest.getByLabel('Contraseña', { exact: true }).fill(fixture.password);
  await guest.getByRole('button', { name: 'términos y condiciones', exact: true }).click();
  await guest.getByRole('button', { name: 'Aceptar términos', exact: true }).click();
  await guest.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(guest.getByRole('heading', { name: 'Ingresa tu código' })).toBeVisible();
  let guestMail;
  await expect.poll(async () => {
    const list = await (await request.get(`${mailbox}/api/v1/messages`)).json();
    guestMail = list.messages?.find(m => m.Subject === 'Tu código de seguridad de SRD' && m.To.some(t => t.Address === email));
    return !!guestMail;
  }).toBe(true);
  const guestContent = await (await request.get(`${mailbox}/api/v1/message/${guestMail.ID}`)).json();
  await guest.getByLabel('Código de verificación').fill(guestContent.Text.match(/\b\d{6}\b/)[0]);
  await guest.getByRole('button', { name: 'Confirmar código' }).click();
  await expect(guest.getByRole('button', { name: 'Home', exact: true })).toBeVisible();
  const principal = await (await guestContext.request.get('/api/v1/me')).json();
  expect(principal.data.organization.code).toBe(code);
  expect(principal.data.role).toBe('admin');
  expect((await guestContext.request.get('/api/v1/platform/organizations')).status()).toBe(403);
  page.on('dialog', dialog => dialog.accept());
  await row.getByRole('button', { name: 'Suspender', exact: true }).click();
  await expect(row.getByRole('cell', { name: 'Suspendida', exact: true })).toBeVisible();
  expect((await request.get(`/api/v1/organizations/${code}`)).status()).toBe(404);
  expect((await guestContext.request.get('/api/v1/persons')).status()).toBe(403);
  await row.getByRole('button', { name: 'Activar', exact: true }).click();
  await expect(row.getByRole('cell', { name: 'Activa', exact: true })).toBeVisible();
  expect((await request.get(`/api/v1/organizations/${code}`)).status()).toBe(200);
  expect((await guestContext.request.get('/api/v1/persons')).status()).toBe(200);
  await panel.scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.local/platform-desktop.png' });
  await page.setViewportSize({ width: 360, height: 800 });
  await expect.poll(() => page.locator('.sidebar').evaluate(el => el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await panel.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '.local/platform-mobile.png', animations: 'disabled' });
  expect(errors).toEqual([]);
  } finally { await guestContext.close(); }
});
