import { test, expect } from '@playwright/test';
import fs from 'node:fs';

const fixture = JSON.parse(fs.readFileSync(process.env.SRD_BROWSER_FIXTURE));
const mailUrl = process.env.SRD_MAILPIT_URL || 'http://localhost:8025';

async function login(page, role) {
  await page.goto(`/j/${fixture.codeA}/login`);
  await page.getByLabel('Correo electrónico', { exact: true }).fill(fixture.users[role].email);
  await page.getByLabel('Contraseña', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'términos y condiciones', exact: true }).click();
  await page.getByRole('button', { name: 'Aceptar términos', exact: true }).click();
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Ingresa tu código' })).toBeVisible();
  let message;
  await expect.poll(async () => {
    const list = await (await page.request.get(`${mailUrl}/api/v1/messages`)).json();
    message = list.messages?.find(item => item.Subject === 'Tu código de seguridad de SRD' && item.To.some(to => to.Address === fixture.users[role].email));
    return !!message;
  }, { timeout: 85000 }).toBe(true);
  const content = await (await page.request.get(`${mailUrl}/api/v1/message/${message.ID}`)).json();
  await page.getByLabel('Código de verificación').fill(content.Text.match(/\b\d{6}\b/)[0]);
  await page.getByRole('button', { name: 'Confirmar código' }).click();
  await expect(page.locator('.sidebar').getByRole('button', { name: 'Home', exact: true })).toBeVisible();
}

test('treasury opening, entries, reversal, receipt and role isolation', async ({ page, browser }) => {
  test.setTimeout(240000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page, 'treasurer');
  await page.locator('.sidebar').getByRole('button', { name: 'Tesorería' }).click();
  await expect(page.getByRole('heading', { name: 'Tesorería' })).toBeVisible();
  await page.getByRole('button', { name: 'Registrar apertura' }).click();
  let dialog = page.getByRole('dialog', { name: 'Registrar apertura' });
  await dialog.getByLabel('Importe COP').fill('100.00');
  await dialog.getByLabel('Concepto').fill('Apertura ficticia');
  await dialog.getByRole('button', { name: 'Guardar y generar comprobante' }).click();
  await expect(page.getByRole('dialog', { name: 'Comprobante TES-000001' })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar' }).click();
  await expect(page.locator('.treasury-summary').getByText('$ 100,00')).toHaveCount(2);
  await page.getByRole('button', { name: 'Registrar ingreso o egreso' }).click();
  dialog = page.getByRole('dialog', { name: 'Registrar movimiento' });
  await dialog.getByLabel('Importe COP').fill('25.50');
  await dialog.getByLabel('Concepto').fill('Donación ficticia');
  await dialog.getByRole('button', { name: 'Guardar y generar comprobante' }).click();
  await expect(page.getByRole('dialog', { name: 'Comprobante TES-000002' })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar' }).click();
  await page.getByRole('button', { name: 'Registrar ingreso o egreso' }).click();
  dialog = page.getByRole('dialog', { name: 'Registrar movimiento' });
  await dialog.getByLabel('Tipo').selectOption('expense');
  await dialog.getByLabel('Importe COP').fill('20.25');
  await dialog.getByLabel('Concepto').fill('Compra ficticia');
  await dialog.getByRole('button', { name: 'Guardar y generar comprobante' }).click();
  await expect(page.getByRole('dialog', { name: 'Comprobante TES-000003' })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar' }).click();
  await expect(page.locator('.treasury-summary').getByText('$ 105,25')).toBeVisible();
  await page.getByRole('row').filter({ hasText: 'Compra ficticia' }).getByRole('button', { name: 'Ver comprobante' }).click();
  dialog = page.getByRole('dialog', { name: 'Comprobante TES-000003' });
  await dialog.getByLabel('Motivo del reverso').fill('Corrección de compra ficticia');
  await dialog.getByRole('button', { name: 'Registrar reverso' }).click();
  await expect(page.getByRole('dialog', { name: 'Comprobante TES-000004' })).toBeVisible();
  dialog = page.getByRole('dialog', { name: 'Comprobante TES-000004' });
  await dialog.getByLabel('Nombre del archivo (opcional)').fill('Reunión/Septiembre?.xlsx.pdf');
  await expect(dialog.getByRole('button', { name: 'Descargar comprobante PDF' })).toBeDisabled();
  await dialog.getByLabel('Confirmo el nombre del archivo').check();
  const receiptResponsePromise = page.waitForResponse(response => response.url().includes('/api/v1/treasury/movements/') && response.request().method() === 'GET');
  const pdfPromise = page.waitForEvent('download');
  await page.getByRole('dialog').getByRole('button', { name: 'Descargar comprobante PDF' }).click();
  const receiptResponse = await receiptResponsePromise;
  expect(receiptResponse.status()).toBe(200);
  const receiptData = (await receiptResponse.json()).data;
  expect(receiptData.filename).toBe('Reunion-Septiembre.pdf');
  const downloadedReceipt = receiptData.receipt;
  expect(downloadedReceipt.receipt).toBe('TES-000004');
  expect(downloadedReceipt.reverses_id).toBeTruthy();
  const pdf = await pdfPromise;
  expect(pdf.suggestedFilename()).toBe('Reunion-Septiembre.pdf');
  const pdfBytes = fs.readFileSync(await pdf.path());
  expect(pdfBytes.subarray(0, 5).toString()).toBe('%PDF-');
  fs.writeFileSync('.local/treasury-receipt-proof.pdf', pdfBytes);
  const excelPromise = page.waitForEvent('download');
  await dialog.getByRole('button', { name: 'Descargar comprobante Excel' }).click();
  const excel = await excelPromise;
  expect(excel.suggestedFilename()).toBe('Reunion-Septiembre.xlsx');
  const excelBytes = fs.readFileSync(await excel.path());
  expect(excelBytes.subarray(0, 2).toString()).toBe('PK');
  expect(excelBytes.includes(Buffer.from('TES-000004'))).toBe(true);
  expect(excelBytes.includes(Buffer.from(downloadedReceipt.reverses_id))).toBe(true);
  expect(excelBytes.includes(Buffer.from('20.25'))).toBe(true);
  expect(excelBytes.includes(Buffer.from('125.50'))).toBe(true);
  expect(excelBytes.includes(Buffer.from('Apertura ficticia'))).toBe(false);
  fs.writeFileSync('.local/treasury-receipt-proof.xlsx', excelBytes);
  await page.setViewportSize({ width: 360, height: 800 });
  await expect(dialog.getByRole('button', { name: 'Descargar comprobante Excel' })).toBeVisible();
  await dialog.getByRole('button', { name: 'Descargar comprobante Excel' }).scrollIntoViewIfNeeded();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(2);
  await page.screenshot({ path: '.local/treasury-receipt-downloads-mobile.png' });
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar' }).click();
  await expect(page.locator('.treasury-summary').getByText('$ 125,50')).toBeVisible();
  const viewerContext = await browser.newContext({ baseURL: process.env.SRD_TEST_URL || 'http://localhost:8080' });
  try {
    const viewer = await viewerContext.newPage();
    await login(viewer, 'viewer');
    await expect(viewer.locator('.sidebar').getByRole('button', { name: 'Tesorería' })).toHaveCount(0);
    const response = await viewer.request.get('/api/v1/treasury');
    expect(response.status()).toBe(403);
    expect((await viewer.request.get(`/api/v1/treasury/movements/${downloadedReceipt.id}`)).status()).toBe(403);
    expect((await viewer.request.get(`/api/v1/treasury/movements/${downloadedReceipt.id}/pdf`)).status()).toBe(403);
    expect((await viewer.request.get(`/api/v1/treasury/movements/${downloadedReceipt.id}/xlsx`)).status()).toBe(403);
  } finally { await viewerContext.close(); }
  await page.setViewportSize({ width: 360, height: 800 });
  await expect(page.getByRole('heading', { name: 'Tesorería' })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(2);
  expect(errors).toEqual([]);
});
