<?php

use App\Http\Controllers\GatewayController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::post('internal/v1/chat/terminate-session', [GatewayController::class, 'terminateChatSession'])
    ->middleware('internal')
    ->withoutMiddleware(\Illuminate\Foundation\Http\Middleware\ValidateCsrfToken::class);

Route::prefix('api/v1')->middleware('throttle:srd-global')->group(function () {
    Route::get('system/services', [GatewayController::class, 'serviceStatus'])->middleware('throttle:10,1,srd-status:');
    Route::get('system/schedulers', [GatewayController::class, 'schedulerStatus'])->middleware('throttle:10,1,srd-schedulers:');
    Route::get('system/audit-deliveries', [GatewayController::class, 'auditDeliveryOverview'])->middleware('throttle:10,1,srd-audit-delivery-overview:');
    Route::get('system/calendar-deliveries', fn (Request $r, GatewayController $g) => $g->forward($r, 'calendar', 'delivery-status'))->middleware('throttle:10,1,srd-calendar-delivery-status:');
    Route::get('system/mail-deliveries', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'mail-delivery-status'))->middleware('throttle:10,1,srd-mail-delivery-status:');
    Route::post('system/mail-deliveries/{type}/{id}/retry', fn (Request $r, GatewayController $g, string $type, string $id) => $g->forward($r, 'identity', 'mail-delivery-status/'.$type.'/'.$id.'/retry'))->whereIn('type', ['invitations', 'security-notices'])->whereUuid('id')->middleware('throttle:10,1,srd-mail-delivery-retry:');
    Route::post('system/calendar-deliveries/{id}/retry', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'calendar', 'delivery-status/'.$id.'/retry'))->whereUuid('id')->middleware('throttle:10,1,srd-calendar-delivery-retry:');
    Route::get('folder-access', fn (Request $r, GatewayController $g) => $g->forward($r,'files','folder-access'));
    Route::get('folder-quota', fn (Request $r, GatewayController $g) => $g->forward($r,'files','folder-quota'));
    Route::put('folder-access', fn (Request $r, GatewayController $g) => $g->folderAccessUpdate($r));
    Route::get('members/folder-readers', fn (Request $r, GatewayController $g) => $g->forward($r,'identity','members/folder-readers'));
    Route::match(['GET','POST'], 'folder-documents', fn (Request $r, GatewayController $g) => $g->forward($r,'files','folder-documents'));
    Route::get('folder-documents/search', fn (Request $r, GatewayController $g) => $g->forward($r,'files','folder-documents/search'));
    Route::patch('folder-documents/{id}', fn (Request $r, GatewayController $g,string $id) => $g->forward($r,'files','folder-documents/'.$id))->whereUuid('id');
    Route::post('folder-documents/{id}/move', fn (Request $r, GatewayController $g,string $id) => $g->forward($r,'files','folder-documents/'.$id.'/move'))->whereUuid('id');
    Route::get('folder-documents/{id}/download', fn (Request $r, GatewayController $g,string $id) => $g->forward($r,'files','folder-documents/'.$id.'/download'))->whereUuid('id');
    Route::get('folder-documents/{id}/preview', fn (Request $r, GatewayController $g,string $id) => $g->forward($r,'files','folder-documents/'.$id.'/preview'))->whereUuid('id');
    Route::delete('folder-documents/{id}', fn (Request $r, GatewayController $g,string $id) => $g->forward($r,'files','folder-documents/'.$id))->whereUuid('id');
    Route::match(['GET', 'POST'], 'folders', fn (Request $r, GatewayController $g) => $g->forward($r, 'files', 'folders'));
    Route::post('folders/{id}/move', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'files', 'folders/'.$id.'/move'))->whereUuid('id');
    Route::patch('folders/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'files', 'folders/'.$id))->whereUuid('id');
    Route::delete('folders/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'files', 'folders/'.$id))->whereUuid('id');
    Route::get('assets/{id}/photos', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'files', 'assets/'.$id.'/photos'))->whereUuid('id');
    Route::get('assets/export', fn (Request $r, GatewayController $g) => $g->forward($r, 'inventory', 'assets/export'))->middleware('throttle:5,1,srd-export:');
    Route::get('assets/{id}/movements/export', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'inventory', 'assets/'.$id.'/movements/export'))->whereUuid('id')->middleware('throttle:5,1,srd-export:');
    Route::get('assets/{id}/movements/export-pdf', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'inventory', 'assets/'.$id.'/movements/export-pdf'))->whereUuid('id')->middleware('throttle:5,1,srd-export:');
    Route::get('assets/export-pdf', fn (Request $r, GatewayController $g) => $g->forward($r, 'inventory', 'assets/export-pdf'))->middleware('throttle:5,1,srd-export:');
    Route::match(['GET', 'PUT', 'DELETE'], 'assets/{id}/photos/{slot}', fn (Request $r, GatewayController $g, string $id, string $slot) => $g->forward($r, 'files', 'assets/'.$id.'/photos/'.$slot))->whereUuid('id')->whereIn('slot', ['front','side','detail']);
    Route::get('persons/{id}/photos', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'files', 'persons/'.$id.'/photos'))->whereUuid('id');
    Route::match(['GET', 'PUT', 'DELETE'], 'persons/{id}/photos/{slot}', fn (Request $r, GatewayController $g, string $id, string $slot) => $g->forward($r, 'files', 'persons/'.$id.'/photos/'.$slot))->whereUuid('id')->whereIn('slot', ['person','document','property']);
    Route::match(['GET', 'PUT'], 'person-fields', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'person-fields'));
    Route::match(['GET', 'PUT'], 'person-filter-settings', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'person-filter-settings'));
    Route::match(['GET', 'PUT'], 'planilla-settings', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'planilla-settings'));
    Route::match(['GET', 'PUT'], 'person-positions', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'person-positions'));
    Route::get('audit-delivery/{service}', fn (Request $r, GatewayController $g, string $service) => $g->forward($r, $service, 'outbox-status'))->whereIn('service', ['identity', 'configuration', 'records', 'files', 'calendar', 'notifications', 'treasury', 'inventory', 'chat']);
    Route::post('audit-delivery/{service}/{id}/retry', fn (Request $r, GatewayController $g, string $service, string $id) => $g->forward($r, $service, 'outbox-status/'.$id.'/retry'))->whereIn('service', ['identity', 'configuration', 'records', 'files', 'calendar', 'notifications', 'treasury', 'inventory', 'chat'])->whereUuid('id')->middleware('throttle:10,1,srd-audit-retry:');
    Route::match(['GET', 'POST'], 'conversations', fn (Request $r, GatewayController $g) => $g->forward($r, 'chat', 'conversations'));
    Route::get('conversations/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'chat', 'conversations/'.$id))->whereUuid('id');
    Route::match(['GET', 'POST'], 'conversations/{id}/messages', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'chat', 'conversations/'.$id.'/messages'))->whereUuid('id');
    Route::post('conversations/{id}/receipts', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'chat', 'conversations/'.$id.'/receipts'))->whereUuid('id');
    Route::get('chat/broadcast-config', [GatewayController::class, 'chatBroadcastConfig']);
    Route::post('chat/broadcast-auth', [GatewayController::class, 'chatBroadcastAuthorize'])
        ->middleware('throttle:30,1,srd-chat-broadcast:');
    Route::get('assets', fn (Request $r, GatewayController $g) => $g->forward($r, 'inventory', 'assets'));
    Route::post('assets', fn (Request $r, GatewayController $g) => $g->forward($r, 'inventory', 'assets'));
    Route::get('assets/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'inventory', 'assets/'.$id))->whereUuid('id');
    Route::patch('assets/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'inventory', 'assets/'.$id))->whereUuid('id');
    Route::post('assets/{id}/movements', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'inventory', 'assets/'.$id.'/movements'))->whereUuid('id');
    Route::post('assets/{id}/retire', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'inventory', 'assets/'.$id.'/retire'))->whereUuid('id');
    Route::get('treasury', fn (Request $r, GatewayController $g) => $g->forward($r, 'treasury', 'treasury'));
    Route::get('treasury/export', fn (Request $r, GatewayController $g) => $g->forward($r, 'treasury', 'treasury/export'))->middleware('throttle:5,1,srd-export:');
    Route::get('treasury/export-pdf', fn (Request $r, GatewayController $g) => $g->forward($r, 'treasury', 'treasury/export-pdf'))->middleware('throttle:5,1,srd-export:');
    Route::post('treasury/opening', fn (Request $r, GatewayController $g) => $g->forward($r, 'treasury', 'treasury/opening'));
    Route::post('treasury/movements', fn (Request $r, GatewayController $g) => $g->forward($r, 'treasury', 'treasury/movements'));
    Route::get('treasury/movements/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'treasury', 'treasury/movements/'.$id))->whereUuid('id');
    Route::get('treasury/movements/{id}/pdf', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'treasury', 'treasury/movements/'.$id.'/pdf'))->whereUuid('id')->middleware('throttle:5,1,srd-export:');
    Route::get('treasury/movements/{id}/xlsx', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'treasury', 'treasury/movements/'.$id.'/xlsx'))->whereUuid('id')->middleware('throttle:5,1,srd-export:');
    Route::post('treasury/movements/{id}/reverse', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'treasury', 'treasury/movements/'.$id.'/reverse'))->whereUuid('id');
    Route::match(['GET', 'PUT'], 'calendar-settings', fn (Request $r, GatewayController $g) => $g->forward($r, 'calendar', 'settings'));
    Route::match(['GET', 'POST'], 'calendar-events', fn (Request $r, GatewayController $g) => $g->forward($r, 'calendar', 'events'));
    Route::get('calendar-events/search', fn (Request $r, GatewayController $g) => $g->forward($r, 'calendar', 'events/search'));
    Route::match(['GET', 'PATCH'], 'calendar-events/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'calendar', 'events/'.$id))->whereUuid('id');
    Route::post('calendar-events/{id}/cancel', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'calendar', 'events/'.$id.'/cancel'))->whereUuid('id');
    Route::get('calendar-invitations', fn (Request $r, GatewayController $g) => $g->forward($r, 'calendar', 'invitations'));
    Route::post('calendar-invitations/{id}/respond', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'calendar', 'invitations/'.$id.'/respond'))->whereUuid('id');
    Route::get('notifications', fn (Request $r, GatewayController $g) => $g->forward($r, 'notifications', 'notifications'));
    Route::match(['GET', 'PUT'], 'notification-preferences', fn (Request $r, GatewayController $g) => $g->forward($r, 'notifications', 'preferences'));
    Route::post('notifications/{id}/read', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'notifications', 'notifications/'.$id.'/read'))->whereUuid('id');
    Route::delete('notifications/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'notifications', 'notifications/'.$id))->whereUuid('id');
    Route::get('quick-links', fn (Request $r, GatewayController $g) => $g->forward($r, 'configuration', 'quick-links'));
    Route::patch('quick-links/{scope}', fn (Request $r, GatewayController $g, string $scope) => $g->forward($r, 'configuration', 'quick-links/'.$scope))->whereIn('scope', ['organization', 'personal']);
    Route::post('platform/organizations/{id}/administrators', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'identity', 'platform/organizations/'.$id.'/administrators'))->whereUuid('id');
    Route::get('platform/accounts', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'platform/accounts'));
    Route::patch('platform/accounts/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'identity', 'platform/accounts/'.$id))->whereUuid('id');
    Route::match(['GET', 'POST'], 'platform/organizations', fn (Request $r, GatewayController $g) => $g->forward($r, 'configuration', 'platform/organizations'));
    Route::patch('platform/organizations/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'configuration', 'platform/organizations/'.$id))->whereUuid('id');
    Route::get('csrf', fn () => ['data' => ['token' => csrf_token()]]);
    Route::get('organizations/{code}', [GatewayController::class, 'publicConfig']);
    Route::post('auth/{action}', [GatewayController::class, 'auth'])->middleware('throttle:20,1,srd-auth:');
    Route::get('me', [GatewayController::class, 'me']);
    Route::get('contacts', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'contacts'));
    Route::post('presence/heartbeat', [GatewayController::class, 'presence']);
    Route::post('invitations/inspect', fn (Request $r, GatewayController $g) => $g->invitation($r, 'inspect'))->middleware('throttle:20,1,srd-invitation-public:');
    Route::post('invitations/accept', fn (Request $r, GatewayController $g) => $g->invitation($r, 'accept'))->middleware('throttle:20,1,srd-invitation-public:');
    Route::get('members', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'members'));
    Route::patch('members/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'identity', 'members/'.$id))->whereUuid('id');
    Route::match(['GET', 'POST'], 'invitations', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'invitations'));
    Route::delete('invitations/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'identity', 'invitations/'.$id))->whereUuid('id');
    Route::get('dashboard', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'dashboard'));
    Route::match(['GET', 'POST'], 'persons', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'persons'));
    Route::get('persons/export', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'persons/export'))->middleware('throttle:5,1,srd-export:');
    Route::get('persons/{id}/xlsx', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'records', 'persons/'.$id.'/xlsx'))->whereUuid('id')->middleware('throttle:5,1,srd-export:');
    Route::get('persons/{id}/pdf', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'records', 'persons/'.$id.'/pdf'))->whereUuid('id')->middleware('throttle:5,1,srd-export:');
    Route::get('persons/export-pdf', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'persons/export-pdf'))->middleware('throttle:5,1,srd-export:');
    Route::get('persons/planilla', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'persons/planilla'))->middleware('throttle:5,1,srd-export:');
    Route::get('persons/planilla-preview', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'persons/planilla-preview'))->middleware('throttle:5,1,srd-export:');
    Route::get('persons/planilla-pdf', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'persons/planilla-pdf'))->middleware('throttle:5,1,srd-export:');
    Route::get('persons/lookup', fn (Request $r, GatewayController $g) => $g->forward($r, 'records', 'persons/lookup'));
    Route::match(['GET', 'PATCH', 'DELETE'], 'persons/{id}', fn (Request $r, GatewayController $g, string $id) => $g->forward($r, 'records', 'persons/'.$id))->whereUuid('id');
    Route::patch('organization', fn (Request $r, GatewayController $g) => $g->forward($r, 'configuration', 'organization'));
    Route::post('organization/terms', fn (Request $r, GatewayController $g) => $g->forward($r, 'configuration', 'organization/terms'));
    Route::get('audit-events', fn (Request $r, GatewayController $g) => $g->forward($r, 'audit', 'events'));
    Route::get('audit-events/export', fn (Request $r, GatewayController $g) => $g->forward($r, 'audit', 'events/export'))->middleware('throttle:5,1,srd-export:');
    Route::get('audit-events/export-pdf', fn (Request $r, GatewayController $g) => $g->forward($r, 'audit', 'events/export-pdf'))->middleware('throttle:5,1,srd-export:');
    Route::patch('profile', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'profile'));
    Route::post('profile/email-change', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'profile/email-change'))->middleware('throttle:10,1,srd-email:');
    Route::post('profile/email-change/resend', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'profile/email-change/resend'))->middleware('throttle:10,1,srd-email:');
    Route::post('profile/email-change/confirm', fn (Request $r, GatewayController $g) => $g->forward($r, 'identity', 'profile/email-change/confirm'))->middleware('throttle:10,1,srd-email:');
    Route::get('releases', function (Request $r, GatewayController $g) {
        $g->me($r);

        return ['data' => []];
    });
});
